modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = [" ₁", " ₂", " ₃", " ₄", " ₅", " ₆", " ₇", " ₈", " ₉"]
layouts = ["MainAndVertStack", "Monocle"]
layout_mode = "Tag"
scratchpad = [
    {name = "ScratchpadTerminal", value = "~/.local/bin/alacritty", x = 0.055, y = 65, width = 0.89, height = 0.34}
]
#[[scratchpad]]
#name = "Alacritty" # This is the name which is referenced when calling (case-sensitive)
#value = "~/.local/bin/alacritty" # The command to load the application if it isn't started
# x, y, width, height are in pixels when an integer is inputted or a percentage when a float is inputted.
# These values are relative to the size of the workspace, and will be restricted depending on the workspace size.
#x = 860
#y = 390
#height = 300
#width = 200
window_rules = [
    {window_class = "Firefox-esr", spawn_on_tag = 1},
    {window_class = "jetbrains-phpstorm", spawn_on_tag = 2},
    {window_class = "org.gnome.Nautilus", spawn_on_tag = 3},
    {window_class = "Mysql-workbench-bin", spawn_on_tag = 4},
    {window_class = "DBeaver", spawn_on_tag = 4},
    {window_class = "robo3t", spawn_on_tag = 4},
    {window_class = "Gimp-2.10", spawn_on_tag = 5},
    {window_class = "VirtualBox Manager", spawn_on_tag = 6},
    {window_class = "Virt-manager", spawn_on_tag = 6},
    {window_class = "org.remmina.Remmina", spawn_on_tag = 6},
    {window_class = "Microsoft Teams - Preview", spawn_on_tag = 7},
    {window_class = "Code", spawn_on_tag = 8},
    {window_class = "Sublime_text", spawn_on_tag = 9},
    {window_title = "Pavucontrol", spawn_floating = true}
]
disable_current_tag_swap = true 
disable_tile_drag = false
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "flameshot gui"
modifier = []
key = "XF86XK_Launch8"

[[keybind]]
command = "Execute"
value = "flameshot gui"
modifier = []
key = "Print"

[[keybind]]
command = "Execute"
value = "brightnessctl --device='intel_backlight' set 2%-"
modifier = []
key = "XF86XK_MonBrightnessDown"

[[keybind]]
command = "Execute"
value = "brightnessctl --device='intel_backlight' set +2%"
modifier = []
key = "XF86XK_MonBrightnessUp"

[[keybind]]
command = "Execute"
value = "pactl set-source-mute 0 toggle"
modifier = []
key = "XF86XK_AudioMicMute"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume 0 +3%"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume 0 -3%"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute 0 toggle"
modifier = []
key = "XF86XK_AudioMute"

[[keybind]]
command = "ToggleScratchPad"
value = "ScratchpadTerminal"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "Execute"
value = "pavucontrol"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "i"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "Execute"
value = "firefox-esr"
modifier = ["modkey"]
key = "b"

[[keybind]]
command = "Execute"
value = "nautilus -w"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "Execute"
value = "~/.config/scripts/start-rofi.sh"
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "Execute"
value = "~/.local/bin/alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "terminator"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", "Shift"]
key = "t"


[[keybind]]
command = "ToggleFloating"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Control"]
key = "r"

[[keybind]]
command = "Execute"
value = "light-locker-command -l"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
value = ""
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"
